DROP TABLE EMPLOYEE;
DROP TABLE EMAIL;

DROP TABLE EMPLOYEENAME;

DROP TABLE EMPLOYEEADDRESS;

DROP TABLE PHONECONTACT;



CREATE TABLE EMPLOYEE(EMP_ID integer NOT NULL AUTO_INCREMENT, PRIMARY KEY(EMP_ID));



CREATE TABLE EMAIL(ID integer NOT NULL AUTO_INCREMENT, EMAIL_ID VARCHAR2(20), EMP_ID INTEGER NOT NULL, PRIMARY KEY(ID)
,FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));


CREATE TABLE EMPLOYEENAME(ID integer NOT NULL AUTO_INCREMENT, FIRSTNAME VARCHAR2(20), LASTNAME VARCHAR2(20), MIDDLENAME VARCHAR2(20), EMP_ID INTEGER NOT NULL, PRIMARY KEY(ID)
,FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));


CREATE TABLE EMPLOYEEADDRESS(ID integer NOT NULL AUTO_INCREMENT, STATE VARCHAR2(20), CITY VARCHAR2(20), STREET VARCHAR2(20), ZIP VARCHAR2(20), EMP_ID INTEGER NOT NULL, PRIMARY KEY(ID)
,FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));


CREATE TABLE PHONECONTACT(ID integer NOT NULL AUTO_INCREMENT, TYPE VARCHAR2(20), NUMBER VARCHAR2(20), EMP_ID INTEGER NOT NULL, PRIMARY KEY(ID)
,FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));